#pragma once

#include <cmath>

const unsigned int NUM_SIM_RUNS = 10;

const unsigned int DAY = 24;
const unsigned int WEEK = DAY * 7;
const unsigned int MONTH = DAY * 30;
const unsigned int YEAR = DAY * 365;

const unsigned int INITIAL_WORK_HOURS_DAILY = 8;
const unsigned int INITIAL_WORK_DAYS_WEEKLY = 5;
const double INITIAL_ACCOUNT_DURATION = 2 * MONTH;
const int WORK_HOURS_UPDATE_START = YEAR;
const int WORK_HOURS_UPDATE_PERIOD = MONTH;
const double INEFFICIENCY_OF_WORK = 1.5;

const unsigned int STARTING_NUM_PEOPLE = 1000;
const unsigned int STARTING_NUM_PRODUCTS = 100;
const unsigned int STARTING_PRODUCTS_PER_MACHINE = 5;
const unsigned int STARTING_NUM_PRODUCERS = STARTING_NUM_PRODUCTS;
const unsigned int STARTING_NUM_DISTRIBUTORS = STARTING_NUM_PRODUCTS;

const int INITIAL_AGE = 17 * YEAR;
const double RANDOM_RETIREMENT_CHANCE = 8.3e-7;
const int GUARANTEED_RETIREMENT_AGE = 67 * YEAR;
const double AVERAGE_RETIREMENT_AGE = (
        1 - pow(1 - RANDOM_RETIREMENT_CHANCE, GUARANTEED_RETIREMENT_AGE)) /
    RANDOM_RETIREMENT_CHANCE +
    INITIAL_AGE; // approx 62 years in hours

const int PRODUCT_ABILITY_COUNT_MAX = 1;
const int PRODUCT_ORDER_SIZE_MIN = 1;
const int PRODUCT_ORDER_SIZE_MAX = 10;
const int PRODUCT_NUM_INPUTS_MIN = 1;
const int PRODUCT_NUM_INPUTS_MAX = STARTING_NUM_PRODUCTS / 2;
const double PRODUCT_INPUT_PER_UNIT_MIN = 0.1;
const double PRODUCT_INPUT_PER_UNIT_MAX = 0.25;
const double PRODUCT_INPUT_EPSILON = 0.0001;
const int PRODUCT_NUM_MACHINES_MIN = 0;
const int MAX_PROPORTION_OF_MACHINES_PER_PRODUCT = 5;
const double PRODUCT_LABOR_PER_UNIT_MIN = 0.05;
const double PRODUCT_LABOR_PER_UNIT_MAX = 0.1; 
const double DISTRIBUTION_LABOR_PER_UNIT = 0.0;
const int PRODUCT_CONSUMPTION_GROUP_SIZE = 5;
const double PRODUCT_CONSUMPTION_FALLOFF = 0.97;
const double PRODUCT_CONSUMPTION_MULT = 0.7;
const int PRICE_AVERAGING_WINDOW = MONTH;

const int MACHINE_LIFETIME_MIN = 1000;
const int MACHINE_LIFETIME_MAX = MACHINE_LIFETIME_MIN * 10;

const int FIRM_STOCKPILE_DURATION = 1.5 * WEEK;
const int FIRM_DEMAND_WINDOW_MIN = WEEK;
const int FIRM_DEMAND_WINDOW_MAX = MONTH;
const double FIRM_REORDER_START = 0.25;
const int FIRM_REORDER_ATTEMPTS = 10;
const double DEADLINE_SAFETY_MULT = 0.6;
const int BUSYNESS_AVERAGING_WINDOW = WEEK;
const double TRANSFER_BUSYNESS_THRESHOLD = 0.00;

const int DRAFT_ORDER_REJECTED = -1;
const double PERSON_STOCKPILE_DURATION = WEEK; 
const double PERSON_DEFICIT_THRESHOLD = WEEK / 2.0;
const int PERSON_VARIED_ABILITY_COUNT = 3;
const double PERSON_ABILITY_STDDEV = 0.05;

const double UNHEALTHY_PRODUCTIVITY = 0.5;
const double ANNUAL_SICKNESS_CHANCE = 0.1;
const int AVG_DAYS_TO_RECOVERY = 5;

const char * const LOGGING_DIR = "data";
const char * const LOG_FILE = "data/lte.db";

